### PR TITLE
 Explain the shell used in CodeBuild

### PR DESCRIPTION
**Pull request by TMiguelT**
*Issue #, if available:*

*Description of changes:*
Currently the CodeBuild documentation says:

>You can specify any command that is supported by the build environment's default shell

This implies that by using a custom Docker image like `ubuntu:latest`, it will use that image's login shell, `bash`, to execute commands. However, even with a custom image such as this, the shell used will still be `/bin/sh`. This can be verified by running `ps -p $$` inside any CodeBuild `buildspec.yml` while running inside any Docker container such as `ubuntu`. It seems what is actually happening is that the buildspec file is being `system()` executed, meaning that it uses `/bin/sh` under Linux, as defined by `system(3)` (http://man7.org/linux/man-pages/man3/system.3.html). This is just conjecture, however, and any more accurate explanation would also be helpful.

This PR clarifies which shell is used by CodeBuild, and explains how to access `bash` syntax if needed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by markiver** [comment]
Hello,

Thank you for your suggestion. I am reviewing it with the CodeBuild engineering team. 

We encourage and appreciated pull requests from customers like you because they help us keep the documentation as useful and current as possible.

Your request will be accepted if the engineering team approves the suggested change.

Thank you again,

Mark

**Comment by iversonic** [comment]
Hello,

My apologies for the late follow-up. After working with the engineering team, we updated the documentation to clarify which shell is used.

<<
You can specify any Shell command. In build spec version 0.1, AWS CodeBuild runs each Shell command in a separate instance in the build environment. This means that each command runs in isolation from all other commands. Therefore, by default, you cannot run a single command that relies on the state of any previous commands (for example, changing directories or setting environment variables). To get around this limitation, we recommend you use version 0.2, which solves this issue
>>

Your input is greatly appreciated. This update is public in both the html and Github versions of the user guide, so this PR will be closed.

Thank you again,

Mark

**Comment by markiver** [comment]
Hello,

This topic is now updated using your input. Thank you for your feedback. It's feedback from customers like you who help us keep our documentation as useful and current as possible.

This pull request will now be closed.

Thank you again,

Mark

**Comment by TMiguelT** [comment]
Hmm, now there's no reference to `sh` at all. It's helpful that the documentation no longer implies that it uses the container's default shell, but it could still be more clear about which shell is being used.

**Comment by markiver** [comment]
Hello,

Thank you for your feedback. I get your point. Perhaps we can update "You can specify any Shell command." to be "You can specify any Shell Command Language (sh) command." The intent is for "Shell" or "Shell Command Language" to clarify that the customer uses "sh".

Kind regards,

Mark

**Comment by jumbosushi** [comment]
+1 on specifying which shell is being used

**Pull request closed without merging**
